user/models.py
from datetime import datetime
from typing import Optional
from flask import session
from pydantic import BaseModel as PyModel, EmailStr, Extra, validator, Field


class BaseModel(PyModel):
    id: Optional[int]
    created: Optional[datetime]
    modified: datetime = None

    def dict_without_none(self, **kwargs):
        return self.dict(exclude_none=True, **kwargs)


class StoreInSessionMixin:
    def store_in_session(self: BaseModel, **kwargs):
        session[self.__class__.__name__.lower()] = self.dict()
        session.modified = True

    @classmethod
    def from_session(cls):
        data = session.get(cls.__name__.lower())
        if data is not None:
            return cls(**data)


class ErrorModel(PyModel):
    message: str = "Something Wrong."


class RegisterUser(BaseModel):
    email: str
    password: str
    password_submit: str

    @validator("password_submit")
    def passwords_match(cls, v, values, **kwargs):
        if "password" in values and v != values["password"]:
            raise ValueError("passwords do not match")
        return v

    class Config:
        extra = Extra.ignore


class Login(BaseModel):
    email: str
    password: str

    class Config:
        extra = Extra.ignore


class Auth(StoreInSessionMixin, BaseModel):
    access: str
    refresh: str


class User(StoreInSessionMixin, BaseModel):

    email: str

    is_active: bool = True
    is_superuser: bool = False

user/routes.py
import requests
from flask import Blueprint, redirect, render_template, url_for, request, session
from user.utils import access, get_current_user, create_user
from user.form import RegisterUserForm, LoginForm
from config import Config
from user.models import RegisterUser
from user.permissions import login_required, profile_required

user_blueprint = Blueprint(
    "user",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/user",
)



# def create_user(*args, **kwargs):
#     register_user = RegisterUser(**kwargs)
#     res = requests.post(f"{API}/api/users/register", json=register_user.dict())
#     print(res)
#     return res


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterUserForm()
    if request.method == "POST":
        user = create_user(**form.data)

        return redirect(url_for("index"))
    return render_template("register.html", form=form)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        auth = access(**form.data)
        auth.store_in_session()
        user = get_current_user()
        user.store_in_session()
        return redirect(url_for('index'))
    return render_template("login.html", form=form)


@user_blueprint.route("/logout", methods=["GET"])
def logout():
    session.clear()
    return redirect(url_for("index"))


@user_blueprint.route('/me', methods=["GET", "POST"])
def user():
    user = session.get("user")
    order = requests.get(f"{Config.API_URL}/order/api/order/").json()
    orderlist = []
    for i in range(len(order)):
        if order[i]['user'] == user['id']:
            orderlist.append(order[i])
    if user is None:
        user = get_current_user()
        user.store_in_session()
    return render_template('user.html', user=user, orderlist=orderlist)

user/templates/login.html
{% extends 'base.html' %}

<body>
{% block content %}
    {{ session["user"] }}
    <h1>Login</h1>

    <form action="{{ url_for('user.login') }}" method="POST">
        {{ form.hidden_tag() }}

        <div>{{ form.email.label }}</div>
        <div>{{ form.email }}</div>
        <div>{{ form.password.label }}</div>
        <div>{{ form.password }}</div>
        <div>{{ form.submit }}</div>
    </form>
<!--end frontpage-main-->
<div id="featured-section">
<div id="circles"><img class="first" src="static/images/clean1.png" /> <img src="static/images/built1.png" /> <img src="static/images/reparing.png" /> <img src="static/images/mover2.png" /> </div>
  <div id="footer">
      <p> 2022 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
  </div>
  </div>>
{% endblock %}
</body>
</html>

user/templates/register.html
{% extends 'base.html' %}

<body>
{% block content %}
    {{ session["user"] }}
    <h1>Register</h1>

    <form action="{{ url_for('user.register') }}" method="POST">
        {{ form.hidden_tag() }}

        <div>{{ form.email.label }}</div>
        <div>{{ form.email }}</div>
        <div>{{ form.password.label }}</div>
        <div>{{ form.password }}</div>
        <div>{{ form.password_submit.label }}</div>
        <div>{{ form.password_submit }}</div>
        <div>{{ form.submit }}</div>
    </form>
<!--end frontpage-main-->
<div id="featured-section">
<div id="circles"><img class="first" src="static/images/clean1.png" /> <img src="static/images/built1.png" /> <img src="static/images/reparing.png" /> <img src="static/images/mover2.png" /> </div>
  <div id="footer">
      <p> 2022 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
  </div>
  </div>>
{% endblock %}

</body>
</html>

user/templates/user.html
{% extends 'base.html' %}

<body>
{% block content %}

    <h1>{{ user.email }}</h1>
    <h2>Мои заказы</h2>
        {% for p in orderlist %}
    <div class="card-wrapper">
        <div class="card">
        <h2> <a href="{{ url_for('order.one_order', id=p.id)}}">{{ p.title }} </a></h2>
        <p>{{p.description}}</p>
        <p>{{p.price}}</p>
    </div>
{% endfor %}


<form action="{{ url_for('order.add')}}" style="text-align: center"><button>Оставить заказ</button></form>
    <form action="{{ url_for('executor.add_executor')}}" style="text-align: center"><button>Стать исполнителем</button></form>

<!--end frontpage-main-->
<div id="featured-section">
<div id="circles"><img class="first" src="static/images/clean1.png" /> <img src="static/images/built1.png" /> <img src="static/images/reparing.png" /> <img src="static/images/mover2.png" /> </div>
  <div id="footer">
      <p> 2022 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
  </div>
  </div>>

{% endblock %}

</body>