order/models.py
from datetime import datetime, date
from typing import Optional
from pydantic import BaseModel as PyModel, Extra


class OrderAdd(PyModel):
    user: int
    title: str
    description: str
    city: str
    name: str
    phone_number: str
    price: float
    date_finish: str
    speciality: list

    class Config:
        extra = Extra.ignore


class Order(PyModel):
    pass


class CommentAdd(PyModel):
    body: str
    order: int
    user: int
    is_active: bool

    class Config:
        extra = Extra.ignore


class Comment(PyModel):
    pass


class AddPhoto(PyModel):
    order: int
    photo: str

    class Config:
        extra = Extra.ignore


class Photo(PyModel):
    pass

order/forms.py
from flask_wtf import FlaskForm
from wtforms import FileField, StringField, DateField, SubmitField, SelectMultipleField
from wtforms.validators import DataRequired, EqualTo


class OrderForm(FlaskForm):
    # user = StringField(
    #     "username",
    #     validators=[
    #         DataRequired(),
    #     ],
    # )
    title = StringField(
        "title",
        validators=[
            DataRequired(),
        ],
    )
    description = StringField(
        "description",
        validators=[
            DataRequired(),
        ],
    )
    city = StringField(
        "city",
        validators=[
            DataRequired(),
        ],
    )
    name = StringField(
        "name",
        validators=[
            DataRequired(),
        ],
    )
    phone_number = StringField(
        "phone",
        validators=[
            DataRequired(),
        ],
    )
    photo = FileField(
        "photo",

    )
    price = StringField(
        "price",
        validators=[
            DataRequired(),
        ],
    )
    date_finish = DateField("End Date", format='%Y-%m-%d')
    speciality = SelectMultipleField("специализация", choices=[('1', 'стройка'), ('2', 'уборка')])
    submit = SubmitField("Оставить заказ")


class CommentForm(FlaskForm):
    body = StringField("Ваш комментарий", validators=[
        DataRequired(),
    ], )
    submit = SubmitField("Оставить комментарий")

order/routes.py
from flask import Blueprint, redirect, render_template, url_for, request, session
import json
from user.utils import get_current_user
from order.forms import OrderForm, CommentForm
from order.aws_utils import upload_file_to_s3
import requests
from order.utils import order_add, comment_add, photo_add, order_id
from config import Config


CREATE_ORDER = f"{Config.API_URL}/order/api/order/"
SPECIALITY_ORDER = f"{Config.API_URL}/order/api/specialityorder/"
CREATE_ORDER_COMENT = f'{Config.API_URL}/order/api/order_comments/'
CREATE_ORDER_PHOTO = f'{Config.API_URL}/order/api/orderphotos/'


order_blueprint = Blueprint(
    "order",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/order",
)


@order_blueprint.route("/add", methods=["GET", "POST"])
def add():
    form = OrderForm()
    if form.validate_on_submit():
        user = get_current_user()
        user.store_in_session()
        form_data = dict(form.data)
        form_data.pop("photo")
        form_data['date_finish'] = str(form_data["date_finish"])
        photo = form.photo.data
        link = upload_file_to_s3(photo)
        form_data["photo"] = link
        form_data['speciality'] = list(form_data['speciality'])
        form_data['user'] = int(user.id)
        order_add(**form_data)
        form_data['order'] = order_id()
        s = json.dumps(form_data)
        photo_add(**form_data)
        return redirect(url_for("index"))
    return render_template("add.html", form=form)


@order_blueprint.route("/repair", methods=["GET", "POST"])
def repair():
    filter_spec = request.args.get("speciality")
    if filter_spec:
        a = requests.get(f"{Config.API_URL}/order/api/order/?speciality={filter_spec}").json()
    else:
        a = requests.get(CREATE_ORDER).json()
    b = requests.get(SPECIALITY_ORDER).json()

    return render_template("repair.html", a=a, b=b)


@order_blueprint.route("/<int:id>", methods=["GET", "POST"])
def one_order(id):
    var = requests.get(CREATE_ORDER).json()
    order = var[id - 1]
    form = CommentForm()
    if form.validate_on_submit():
        user = get_current_user()
        user.store_in_session()
        form_data = dict(form.data)
        form_data['user'] = int(user.id)
        form_data['order'] = order['id']
        form_data['is_active'] = True
        comment_add(**form_data)

    com = requests.get(CREATE_ORDER_COMENT).json()
    comments = []
    for i in range(len(com)):
        if com[i]['order'] == order['id']:
            comments.append(com[i])
    photo = requests.get(CREATE_ORDER_PHOTO).json()
    pho = []
    for i in range(len(photo)):
        if photo[i]['order'] == order['id']:
            pho.append(photo[i])

    return render_template("one_order.html", order=order, comments=comments, form=form, pho=pho)

order/templates/add.html
{% extends 'base.html' %}

<body>
{% block content %}

    <h1>ORDER</h1>

    <form action="{{ url_for('order.add') }}" method="POST" enctype="multipart/form-data">
        {{form.errors}}
        {{ form.hidden_tag() }}
        <div>{{ form.speciality.label }}</div>
        <div>{{ form.speciality }}</div>
        <div>{{ form.name.label }}</div>
        <div>{{ form.name }}</div>
        <div>{{ form.title.label }}</div>
        <div>{{ form.title }}</div>
        <div>{{ form.description.label }}</div>
        <div>{{ form.description }}</div>
        <div>{{ form.city.label }}</div>
        <div>{{ form.city }}</div>
        <div>{{ form.phone_number.label }}</div>
        <div>{{ form.phone_number }}</div>
        <div>{{ form.photo.label }}</div>
        <div>{{ form.photo }}</div>
        <div>{{ form.price.label }}</div>
        <div>{{ form.price }}</div>
        <div>{{ form.date_finish.label }}</div>
        <div>{{ form.date_finish }}</div>
        <div>{{ form.submit }}</div>
    </form>

<!--end frontpage-main-->
<div id="featured-section">
<div id="circles"><img class="first" src="static/images/clean1.png" /> <img src="static/images/built1.png" /> <img src="static/images/reparing.png" /> <img src="static/images/mover2.png" /> </div>
  <div id="footer">
      <p> 2022 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
  </div>
  </div>>
{% endblock %}
</body>
</html>

order/templates/one_order.html
{% extends 'base.html' %}
<body>
{% block content %}
{{ super() }}


    <div class="card-wrapper">
        <div class="card">
        <h2> {{ order.title }} </h2>
        <p>{{order.description}}</p>
        <p>{{order.name}}</p>
        <p>{{order.phone_number}}</p>
        <p>{{order.city}}</p>
        <p>{{order.date_finish}}</p>
        <p>{{order.price}}</p>

    </div>
        <div class="card-wrapper">
        <div class="card">
            {% for p in pho %}
                <p><img src= {{p.photo}} width="100" height="111" alt="Письма мастера дзен"></p>
            {% endfor %}
            </div>
    </div>

        <div class="card-wrapper">
        <div class="card">
            {% for p in comments %}
            <p>{{p.user}}</p>
            <h4>{{p.body}}</h4>
            <p>{{p.updated}}</p>
            {% endfor %}

<form method="POST" enctype="multipart/form-data">
        {{form.errors}}
        {{ form.hidden_tag() }}
        <div>{{ form.body.label }}</div>
        <div>{{ form.body }}</div>
        <div>{{ form.submit }}</div>

    </div>
    </div>

{% endblock %}
</body>>