executor/models.py
from pydantic import BaseModel as PyModel, EmailStr, Extra, validator, Field


class RegisterExecutor(PyModel):
    user_id: int
    first_name: str
    last_name: str
    phone_number: str
    city: str
    photo: str
    speciality: list

    @validator('photo')
    def size_is_some(cls, v):
        if v is None:
            raise ValueError('Cannot set photo to None')
        return str(v)

    class Config:
        extra = Extra.ignore


class Executor(PyModel):
    pass


class CommentAdd(PyModel):
    body: str
    executor: int
    user: int
    is_active: bool

    class Config:
        extra = Extra.ignore


class Comment(PyModel):
    pass

executor/forms.py
from flask_wtf import FlaskForm
from wtforms import FileField, StringField, DateField, SubmitField, EmailField, SelectMultipleField
from wtforms.validators import DataRequired, EqualTo


class ExecutorForm(FlaskForm):
    first_name = StringField(
        "Имя",
        validators=[
            DataRequired(),
        ],
    )

    last_name = StringField(
        "Фамилия",
        validators=[
            DataRequired(),
        ],
    )

    phone_number = StringField(
        "Номер телефона",
        validators=[
            DataRequired(),
        ],
    )

    city = StringField(
        "город",
        validators=[
            DataRequired(),
        ],
    )

    photo = FileField(
        "photo",

    )

    speciality = SelectMultipleField("специализация", choices=[('1', 'стройка'), ('2', 'уборка')])
    submit = SubmitField("Стать исполнителем")


class CommentForm(FlaskForm):
    body = StringField("Ваш комментарий", validators=[
        DataRequired(),
    ], )
    submit = SubmitField("Оставить комментарий")

executor/routes.py
from flask import Blueprint, redirect, render_template, url_for, request
from executor.forms import ExecutorForm, CommentForm
import requests
from user.utils import get_current_user
from executor.utils import create_executor,  comment_add, executor_retriev
from config import Config

CREATE_EXECUTOR_SPEC = f"{Config.API_URL}api/executor/?speciality="
EXECUTOR = f"{Config.API_URL}/api/executor/"
SPECIALITY = f"{Config.API_URL}/api/speciality/"
EXECUTOR_COMENT = f'{Config.API_URL}/api/executor_comments/'


executor_blueprint = Blueprint(
    "executor",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/executor",
)


@executor_blueprint.route("/execut", methods=["GET", "POST"])
def exec():
    filter_spec = request.args.get("speciality")
    if filter_spec:
        a = requests.get(f"{Config.API_URL}/api/executor/?speciality={filter_spec}").json()
    else:
        a = requests.get(EXECUTOR).json()
    b = requests.get(SPECIALITY).json()

    return render_template("executors.html", a=a, b=b)


@executor_blueprint.route("/addexecutor", methods=["GET", "POST"])
def add_executor():
    form = ExecutorForm()
    if form.validate_on_submit():
        user = get_current_user()
        user.store_in_session()
        form_data = dict(form.data)
        form_data['speciality'] = list(form_data['speciality'])
        form_data['user_id'] = int(user.id)
        form_data.pop("photo")
        photo = form.photo.data
        from order.aws_utils import upload_file_to_s3
        link = upload_file_to_s3(photo)
        form_data["photo"] = link
        print(form_data)
        create_executor(**form_data)

        return redirect(url_for("index"))
    return render_template("add_executor.html", form=form)


@executor_blueprint.route("/<int:id>", methods=["GET", "POST"])
def one_executor(id):
    executor = executor_retriev(id)
    form = CommentForm()
    if form.validate_on_submit():
        user = get_current_user()
        user.store_in_session()
        form_data = dict(form.data)
        form_data['user_id'] = int(user.id)
        form_data['executor'] = executor['user_id']
        form_data['user'] = form_data["user_id"]
        form_data['is_active'] = True
        comment_add(**form_data)

    com = requests.get(f'{Config.API_URL}/api/executor_comments/').json()
    comments = []
    for i in range(len(com)):
        if com[i]['executor'] == executor['user_id']:
            comments.append(com[i])

    return render_template("one_executor.html", executor=executor, comments=comments, form=form)

executor/templates/add_executor.html
{% extends 'base.html' %}

<body>
{% block content %}
    {{ session["user"] }}


    <form action="{{ url_for('executor.add_executor') }}" method="POST" enctype="multipart/form-data">
        {{form.errors}}
        {{ form.hidden_tag() }}
         <div>{{ form.speciality.label }}</div>
        <div>{{ form.speciality }}</div>
        <div>{{ form.first_name.label }}</div>
        <div>{{ form.first_name }}</div>
        <div>{{ form.last_name.label }}</div>
        <div>{{ form.last_name}}</div>
        <div>{{ form.phone_number.label }}</div>
        <div>{{ form.phone_number }}</div>
        <div>{{ form.city.label }}</div>
        <div>{{ form.city }}</div>
         <div>{{ form.photo.label }}</div>
        <div>{{ form.photo }}</div>



        <div>{{ form.submit }}</div>
    </form>
<!--end frontpage-main-->
<div id="featured-section">
<div id="circles"><img class="first" src="static/images/clean1.png" /> <img src="static/images/built1.png" /> <img src="static/images/reparing.png" /> <img src="static/images/mover2.png" /> </div>
  <div id="footer">
      <p> 2022 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
  </div>
  </div>>
{% endblock %}
</body>
</html>

executor/templates/executors.html
{% extends 'base.html' %}
<body>
{% block content %}
{{ super() }}
<h2 class="main-heading">Поиск исполнителей</h2>
<div class="wrapper">
<sidebar class="sidebar">
     <div class="card-wrapper">
     <div class="card">
<a href="{{ url_for('executor.exec') }}"><h4>Все категории</h4></a>
     </div>
 </div>

    <ul class="list-item">
        {% for c in b %}
        <h2>
            <a href="{{ url_for('executor.exec') }}?speciality={{ c.id }}">{{ c.title }}</a>
        </h2>
     {% endfor %}
    </ul>
</sidebar>
{% for p in a %}
    <div class="card-wrapper">
        <div class="card">
            {% if not session["user"] %}
        <h2>{{ p.first_name }}</h2>
            {% else %}
            <h2> <a href="{{ url_for('executor.one_executor', id=p.user_id)}}">{{ p.first_name }} </a></h2>
            {% endif %}
        <p>{{p.last_name}}</p>
        <p>{{p.city}}</p>
    </div>
{% endfor %}

    </div>
    </div>


{% endblock %}
</body>>

executor/templates/one_executor.html
{% extends 'base.html' %}
<body>
{% block content %}
{{ super() }}


    <div class="card-wrapper">
        <div class="card">
        <h2> {{ executor.first_name}} </h2>
        <p>{{executor.last_name}}</p>
        <p>{{executor.phone_number}}</p>
        <p>{{executor.city}}</p>
        <p><img src= {{executor.photo}} width="100" height="111" alt="Письма мастера дзен"></p>

  <div class="card-wrapper">
        <div class="card">
            {% for p in comments %}
            <p>{{p.user}}</p>
            <h4>{{p.body}}</h4>
            <p>{{p.updated}}</p>
            {% endfor %}

<form method="POST" enctype="multipart/form-data">
        {{form.errors}}
        {{ form.hidden_tag() }}
        <div>{{ form.body.label }}</div>
        <div>{{ form.body }}</div>
        <div>{{ form.submit }}</div>

    </div>
    </div>

    </div>




{% endblock %}
</body>>