order/routes.py
from flask import Blueprint, redirect, render_template, url_for, request, session
import json
from user.utils import get_current_user
from order.forms import OrderForm, CommentForm
from order.aws_utils import upload_file_to_s3
import requests
from order.utils import order_add, comment_add, photo_add, order_id
from config import Config


CREATE_ORDER = f"{Config.API_URL}/order/api/order/"
SPECIALITY_ORDER = f"{Config.API_URL}/order/api/specialityorder/"
CREATE_ORDER_COMENT = f'{Config.API_URL}/order/api/order_comments/'
CREATE_ORDER_PHOTO = f'{Config.API_URL}/order/api/orderphotos/'


order_blueprint = Blueprint(
    "order",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/order",
)


@order_blueprint.route("/add", methods=["GET", "POST"])
def add():
    form = OrderForm()
    if form.validate_on_submit():
        user = get_current_user()
        user.store_in_session()
        form_data = dict(form.data)
        form_data.pop("photo")
        form_data['date_finish'] = str(form_data["date_finish"])
        photo = form.photo.data
        link = upload_file_to_s3(photo)
        form_data["photo"] = link
        form_data['speciality'] = list(form_data['speciality'])
        form_data['user'] = int(user.id)
        order_add(**form_data)
        form_data['order'] = order_id()
        s = json.dumps(form_data)
        photo_add(**form_data)
        return redirect(url_for("index"))
    return render_template("add.html", form=form)


@order_blueprint.route("/repair", methods=["GET", "POST"])
def repair():
    filter_spec = request.args.get("speciality")
    if filter_spec:
        a = requests.get(f"{Config.API_URL}/order/api/order/?speciality={filter_spec}").json()
    else:
        a = requests.get(CREATE_ORDER).json()
    b = requests.get(SPECIALITY_ORDER).json()

    return render_template("repair.html", a=a, b=b)


@order_blueprint.route("/<int:id>", methods=["GET", "POST"])
def one_order(id):
    var = requests.get(CREATE_ORDER).json()
    order = var[id - 1]
    form = CommentForm()
    if form.validate_on_submit():
        user = get_current_user()
        user.store_in_session()
        form_data = dict(form.data)
        form_data['user'] = int(user.id)
        form_data['order'] = order['id']
        form_data['is_active'] = True
        comment_add(**form_data)

    com = requests.get(CREATE_ORDER_COMENT).json()
    comments = []
    for i in range(len(com)):
        if com[i]['order'] == order['id']:
            comments.append(com[i])
    photo = requests.get(CREATE_ORDER_PHOTO).json()
    pho = []
    for i in range(len(photo)):
        if photo[i]['order'] == order['id']:
            pho.append(photo[i])

    return render_template("one_order.html", order=order, comments=comments, form=form, pho=pho)

user/routes.py
import requests
from flask import Blueprint, redirect, render_template, url_for, request, session
from user.utils import access, get_current_user, create_user
from user.form import RegisterUserForm, LoginForm
from config import Config
from user.models import RegisterUser
from user.permissions import login_required, profile_required

user_blueprint = Blueprint(
    "user",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/user",
)



# def create_user(*args, **kwargs):
#     register_user = RegisterUser(**kwargs)
#     res = requests.post(f"{API}/api/users/register", json=register_user.dict())
#     print(res)
#     return res


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterUserForm()
    if request.method == "POST":
        user = create_user(**form.data)

        return redirect(url_for("index"))
    return render_template("register.html", form=form)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        auth = access(**form.data)
        auth.store_in_session()
        user = get_current_user()
        user.store_in_session()
        return redirect(url_for('index'))
    return render_template("login.html", form=form)


@user_blueprint.route("/logout", methods=["GET"])
def logout():
    session.clear()
    return redirect(url_for("index"))


@user_blueprint.route('/me', methods=["GET", "POST"])
def user():
    user = session.get("user")
    order = requests.get(f"{Config.API_URL}/order/api/order/").json()
    orderlist = []
    for i in range(len(order)):
        if order[i]['user'] == user['id']:
            orderlist.append(order[i])
    if user is None:
        user = get_current_user()
        user.store_in_session()
    return render_template('user.html', user=user, orderlist=orderlist)

templates/articles.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Akono | Articles</title>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="styles/style.css" />
<!--[if IE 6]>
<script src="js/ie6-transparency.js"></script>
<script>DD_belatedPNG.fix('#header img, #featured-section h2, #circles img, #frontpage-sidebar .read-more, .blue-bullets li, #sidebar .sidebar-button, #project-content .read-more, .more-link, #contact-form .submit, .jcarousel-skin-tango .jcarousel-next-horizontal, .jcarousel-skin-tango .jcarousel-prev-horizontal, #commentform .submit');</script>
<style>body { behavior: url("styles/ie6-hover-fix.htc"); }</style>
<link rel="stylesheet" href="styles/ie6.css" />
<![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="styles/ie7.css" /><![endif]-->
<!--[if IE 8]><link rel="stylesheet" href="styles/ie8.css" /><![endif]-->
</head>
<body class="page">
<div id="wrap">
  <div id="header"> <img src="images/logo.png" />
    <div id="nav">
      <ul class="menu">
        <li><a href="index.html">Home</a></li>
        <li><a href="page.html">Services</a>
          <ul class="sub-menu">
            <li><a href="#">Branding</a></li>
            <li><a href="#">Online Marketing</a></li>
            <li><a href="#">Search Engine Optimization</a></li>
            <li><a href="#">Web Design</a></li>
          </ul>
        </li>
        <li><a href="portfolio.html">Portfolio</a></li>
        <li class="current_page_item"><a href="articles.html">Articles</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </div>
    <!--end nav-->
  </div>
  <!--end header-->
  <div class="page-headline">Articles</div>
  <div id="main">
    <div id="content">
      <div class="post" >
        <h3 class="post-title"><a href="#">Top Tips For Hiring A Design Agency</a></h3>
        <h3 class="post-meta">1st May 2011 / <a href="#">No Comments &#187;</a></h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a nibh mauris. Mauris interdum, dolor in vulputate tincidunt, mauris lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="#" class="more-link">Read Full Article &raquo;</a></p>
      </div>
      <!--end post-->
      <div class="post-line"></div>
      <div class="post" id="post-77">
        <h3 class="post-title"><a href="#">The Future of HTML5</a></h3>
        <h3 class="post-meta">17th April 2011 / <a href="#">No Comments &#187;</a></h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a nibh mauris. Mauris interdum, dolor in vulputate tincidunt, mauris lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="#" class="more-link">Read Full Article &raquo;</a></p>
      </div>
      <!--end post-->
      <div class="post-line"></div>
      <div class="post">
        <h3 class="post-title"><a href="#">Are You Using CSS3 Yet?</a></h3>
        <h3 class="post-meta">2nd April 2011 / <a href="#">No Comments &#187;</a></h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a nibh mauris. Mauris interdum, dolor in vulputate tincidunt, mauris lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="#" class="more-link">Read Full Article &raquo;</a></p>
      </div>
      <!--end post-->
      <div class="post-line"></div>
      <div class="post">
        <h3 class="post-title"><a href="#">A Guide To Creating Mobile Apps</a></h3>
        <h3 class="post-meta">28th March 2011 / <a href="#">No Comments &#187;</a></h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a nibh mauris. Mauris interdum, dolor in vulputate tincidunt, mauris lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="#" class="more-link">Read Full Article &raquo;</a></p>
      </div>
      <!--end post-->
      <div class="post-line"></div>
      <div class="post">
        <h3 class="post-title"><a href="#">Should Designers Know How To Code?</a></h3>
        <h3 class="post-meta">16th March 2011 / <a href="#">No Comments &#187;</a></h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a nibh mauris. Mauris interdum, dolor in vulputate tincidunt, mauris lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="#" class="more-link">Read Full Article &raquo;</a></p>
      </div>
      <!--end post-->
      <div class="post-line"></div>
      <ul class="post-navigation">
        <li><a href="#">&laquo; Older Articles</a></li>
      </ul>
    </div>
    <!--end content-->
    <div id="sidebar">
      <div id="hire">
        <h3 class="sidebar-title">Want To Hire Akona?</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <a class="sidebar-button" href="contact.html">Contact Us &raquo;</a> </div>
      <!--end hire-->
      <div id="recent-projects">
        <h3>Recent Projects</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
        <div class="portfolio-item"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
        <!--end portfolio-item-->
        <div class="portfolio-item"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
        <!--end portfolio-item-->
        <a class="sidebar-button" href="portfolio.html">All Projects &raquo;</a> </div>
      <!--end recent-projects-->
    </div>
    <!--end sidebar-->
  </div>
  <!--end main-->
  <div id="footer">
    <p class="copyright">Copyright &copy; <a href="#">Domain Name</a> - All Rights Reserved / Design By <a target="_blank" href="http://www.chris-creed.com/">Chris Creed</a></p>
  </div>
  <!--end footer-->
</div>
<!--end wrap-->
</body>
<div class="cache-images"><img src="images/red-button-bg.png" width="0" height="0" alt="" /><img src="images/black-button-bg.png" width="0" height="0" alt="" /></div>
<!--end cache-images-->
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Shuba</title>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}"  />
<link type="text/css" rel="stylesheet"  href="{{ url_for('static', filename='css/skin.css')}}" />

<!--[if IE 6]>

<link rel="stylesheet" href="{{ url_for('static', filename='css/ie6.css')}}"  />
<![endif]-->
<!--[if IE 7]><link type="text/css" href="{{ url_for('static', filename='css/ie7.css')}}" rel="stylesheet" /><![endif]-->

<!--[if IE 8]><link rel="stylesheet" href="static/css/ie8.css" /><![endif]-->
</head>
<body class="home">
<div id="wrap">
  <div id="header"> <a href="/"><img src="static/images/shuba-removebg-preview.png " /></a>

    <div id="nav">
      <ul class="menu">

        <li><a href="/order/repair">Заказы</a>

        </li>

        <li><a href="/executor/execut">Исполнители</a></li>

        {% if not session["user"] %}
        <li><a href='/user/register'>Регистрация</a></li>
        {% else %}
        <li><a href="{{ url_for('user.user')}}">Личный кабинет</a></li>
        {% endif %}

        {% if not session["user"] %}
          <li><a href='/user/login'>Войти</a></li>
        {% else %}
          <li><a href="{{ url_for('user.logout') }}">Выйти</a></li>
          <li> {{ session["user"]["email"] }}</li>
        {% endif %}
       </ul>

    </div>
    <!--end nav-->
  </div>
  <!--end header-->
{% block content %}
{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div id="featured-section">
    <h2>The time of professionals</h2>
    <div id="circles"><img class="first" src="static/images/clean1.png" /> <img src="static/images/built1.png" /> <img src="static/images/reparing.png" /> <img src="static/images/mover2.png" /> </div>
    <!--end circles-->
    <div id="image-slider">
      <ul id="mycarousel" class="jcarousel-skin-tango">

        <li class="first">
          <div class="cardir-wrapper">
        <div class="cardir">
          {% if not session["user"] %}
          <p>{{ order[0].title }}</p>
          {% else %}
          <a href="#"><p>{{ order[0].title }}</p></a>
          {% endif %}

          <p>{{order[0].description}}</p>
          <p>{{order[0].price}}</p>
        </li>
        <li class="first">
          <div class="cardir-wrapper">
        <div class="cardir">

           {% if not session["user"] %}
          <p>{{ order[1].title }}</p>
          {% else %}
          <a href="#"><p>{{ order[1].title }}</p></a>
          {% endif %}
          <p>{{order[1].description}}</p>
          <p>{{order[1].price}}</p>
        </li>


          <li class="first">
          <div class="cardir-wrapper">
        <div class="cardir">

           {% if not session["user"] %}
          <p>{{ order[2].title }}</p>
          {% else %}
          <a href="#"><p>{{ order[2].title }}</p></a>
          {% endif %}
          <p>{{order[2].description}}</p>
          <p>{{order[2].price}}</p>
        </li>


        </li>

      <li><div class="cardir-wrapper">
        <div class="cardir">
          {% if not session["user"] %}
          <p>{{ executor[0].first_name }}</p>
          {% else %}
          <a href="#"><p>{{ executor[0].first_name }}</p></a>
          {% endif %}
          <p>{{speciality[0].title}}</p></li>


         <li><div class="cardir-wrapper">
        <div class="cardir">
          {% if not session["user"] %}
          <p>{{ executor[1].first_name }}</p>
          {% else %}
          <a href="#"><p>{{ executor[1].first_name }}</p></a>
          {% endif %}
          <p>{{speciality[1].title}}</p></li>


        <li><div class="cardir-wrapper">
        <div class="cardir">
          {% if not session["user"] %}
          <p>{{ executor[2].first_name }}</p>
          {% else %}
          <a href="#"><p>{{ executor[2].first_name }}</p></a>
          {% endif %}
          <p>{{speciality[1].title}}</p></li>








      </ul>
    </div>
    <!--end image-slider-->
  </div>
  <!--end featured-section-->
  <div id="frontpage-main">
    <div id="frontpage-content">
      <h3>Почему вы должны выбрать нас?</h3>
      <p>
Вы не пожалеете, если обратитесь к нам по поводу вашего нового проекта. Ниже приведены некоторые преимущества.</p>
      <ul class="blue-bullets">
        <li>Только провереннные пользователи</li>
        <li>Этот cайт лучший в Беларуси</li>
        <li>Вы можете как размещать заказы так и становиться их исполнителем</li>

      </ul>
    </div>
    <!--end frontpage-content-->
    <div id="frontpage-sidebar">
      <h3>Обратная связь</h3>
      <p>Если у вас влзникли какие либо вопросы вы всегда можете связаться с нами. Мы работаем для ывс круглосуточно</p>

      <a class="read-more" href="/contact/cont">Напишите нам &raquo;</a> </div>

    <!--end frontpage-sidebar-->
  </div>
  <!--end frontpage-main-->
  <div id="footer">
    <p> 2022 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>



    </div>
  </div>
  <!--end footer-->
</div>
<!--end wrap-->








{% endblock %}

templates/portfolio.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Akono | Portfolio</title>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="styles/style.css" />
<!--[if IE 6]>
<script src="js/ie6-transparency.js"></script>
<script>DD_belatedPNG.fix('#header img, #featured-section h2, #circles img, #frontpage-sidebar .read-more, .blue-bullets li, #sidebar .sidebar-button, #project-content .read-more, .more-link, #contact-form .submit, .jcarousel-skin-tango .jcarousel-next-horizontal, .jcarousel-skin-tango .jcarousel-prev-horizontal, #commentform .submit');</script>
<style>body { behavior: url("styles/ie6-hover-fix.htc"); }</style>
<link rel="stylesheet" href="styles/ie6.css" />
<![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="styles/ie7.css" /><![endif]-->
<!--[if IE 8]><link rel="stylesheet" href="styles/ie8.css" /><![endif]-->
</head>
<body class="page">
<div id="wrap">
  <div id="header"> <img src="images/logo.png" />
    <div id="nav">
      <ul class="menu">
        <li><a href="index.html">Home</a></li>
        <li><a href="page.html">Services</a>
          <ul class="sub-menu">
            <li><a href="#">Branding</a></li>
            <li><a href="#">Online Marketing</a></li>
            <li><a href="#">Search Engine Optimization</a></li>
            <li><a href="#">Web Design</a></li>
          </ul>
        </li>
        <li class="current_page_item"><a href="portfolio.html">Portfolio</a></li>
        <li><a href="articles.html">Articles</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </div>
    <!--end nav-->
  </div>
  <!--end header-->
  <div class="page-headline">Portfolio</div>
  <div id="main">
    <div id="porfolio-content">
      <div class="portfolio-item first"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
      <div class="portfolio-item"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
      <div class="portfolio-item"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
      <div class="portfolio-item first"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
      <div class="portfolio-item"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
      <div class="portfolio-item"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
      <div class="portfolio-item first"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
      <div class="portfolio-item"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
      <div class="portfolio-item"> <a href="#"><img width="280" height="190" src="images/280x190.gif" alt="" /></a> </div>
      <!--end portfolio-item-->
    </div>
    <!--portfolio-content-->
  </div>
  <!--end main-->
  <div id="footer">
    <p class="copyright">Copyright &copy; <a href="#">Domain Name</a> - All Rights Reserved / Design By <a target="_blank" href="http://www.chris-creed.com/">Chris Creed</a></p>
  </div>
  <!--end footer-->
</div>
<!--end wrap-->
</body>
<div class="cache-images"><img src="images/red-button-bg.png" width="0" height="0" alt="" /><img src="images/black-button-bg.png" width="0" height="0" alt="" /></div>
<!--end cache-images-->
</html>

templates/project.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Akono | Project</title>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="styles/style.css" />
<!--[if IE 6]>
<script src="js/ie6-transparency.js"></script>
<script>DD_belatedPNG.fix('#header img, #featured-section h2, #circles img, #frontpage-sidebar .read-more, .blue-bullets li, #sidebar .sidebar-button, #project-content .read-more, .more-link, #contact-form .submit, .jcarousel-skin-tango .jcarousel-next-horizontal, .jcarousel-skin-tango .jcarousel-prev-horizontal, #commentform .submit');</script>
<style>body { behavior: url("styles/ie6-hover-fix.htc"); }</style>
<link rel="stylesheet" href="styles/ie6.css" />
<![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="styles/ie7.css" /><![endif]-->
<!--[if IE 8]><link rel="stylesheet" href="styles/ie8.css" /><![endif]-->
</head>
<body class="page">
<div id="wrap">
  <div id="header"> <img src="images/logo.png" />
    <div id="nav">
      <ul class="menu">
        <li><a href="index.html">Home</a></li>
        <li><a href="page.html">Services</a>
          <ul class="sub-menu">
            <li><a href="#">Branding</a></li>
            <li><a href="#">Online Marketing</a></li>
            <li><a href="#">Search Engine Optimization</a></li>
            <li><a href="#">Web Design</a></li>
          </ul>
        </li>
        <li><a href="portfolio.html">Portfolio</a></li>
        <li><a href="articles.html">Articles</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </div>
    <!--end nav-->
  </div>
  <!--end header-->
  <div class="page-headline">Project -- [Project Name]</div>
  <div id="main">
    <div id="project-content">
      <div id="project-header">
        <h3 class="title">Project: <span>[Project Name]</span></h3>
        <h3>Start Date: <span>May 2011</span></h3>
        <h3>Completion Date: <span>December 2010</span></h3>
      </div>
      <!--end project-header-->
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea consequat. </p>
      <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <a class="read-more" href="#">Visit Website &raquo;</a> </div>
    <!--end project-content-->
    <div id="project-image-large"> <img src="#" /> </div>
    <!--end project-image-large-->
  </div>
  <!--end main-->
  <div id="footer">
    <p class="copyright">Copyright &copy; <a href="#">Domain Name</a> - All Rights Reserved / Design By <a target="_blank" href="http://www.chris-creed.com/">Chris Creed</a></p>
  </div>
  <!--end footer-->
</div>
<!--end wrap-->
</body>
<div class="cache-images"><img src="images/red-button-bg.png" width="0" height="0" alt="" /><img src="images/black-button-bg.png" width="0" height="0" alt="" /></div>
<!--end cache-images-->
</html>

templates/repair.html
{% extends 'base.html' %}


<body>
{% block content %}
{{ super() }}
<h2 class="main-heading">Поиск работы</h2>
<div class="wrapper">
<sidebar class="sidebar">

 <div class="card-wrapper">
     <div class="card">
<a href="{{ url_for('order.repair') }}"><h4>Все категории</h4></a>
     </div>
 </div>
    <ul class="list-item">

        {% for c in b %}
        <h2>
            <a href="{{ url_for('order.repair') }}?speciality={{ c.id }}">{{ c.title }}</a>
        </h2>
     {% endfor %}
    </ul>
</sidebar>
{% for p in a %}
    <div class="card-wrapper">
        <div class="card">
            {% if not session["user"] %}
            <p>{{p.title}}<p>
            {% else %}
            <h2> <a href="{{ url_for('order.one_order', id=p.id)}}">{{ p.title }} </a></h2>
            {% endif %}
        <p>{{p.description}}</p>
        <p>{{p.price}}</p>
    </div>
{% endfor %}

    </div>
    </div>

<div id="featured-section">
  <div id="footer">
      <p> 2022 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
  </div>
  </div>
{% endblock %}
</body>>